import Head from "next/head";
import ArticleService from "@/service/ArticleService/ArticleService";
import CategoryService from "@/service/CategoryService/CategoryService";
import IArticle from "@/types/Article/IArticle";
import ICategory from "@/types/Category/ICategory";

export default function Home({
  articles,
  categories,
}: {
  articles: IArticle[];
  categories: ICategory[];
}) {
  console.log(articles);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <main></main>
      </div>
    </>
  );
}

export const getServerSideProps = async () => {
  const articles: IArticle[] = await ArticleService.getArticlesLimitSeven();
  const categories: ICategory[] = await CategoryService.getAllCategories();

  return {
    props: {
      articles: articles,
      categories: categories,
    },
  };
};
